// <auto-generated />
using System;
using AfterSalesAI.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AfterSalesAI.Infrastructure.Migrations
{
    [DbContext(typeof(AfterSalesAIDbContext))]
    [Migration("20260910111239_KnowledgeIngestionMetadata")]
    partial class KnowledgeIngestionMetadata
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AfterSalesAI.Domain.Application", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Id")
                        .IsUnique();

                    b.HasIndex("TenantId", "Name")
                        .IsUnique();

                    b.ToTable("applications", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000001"),
                            Description = "Demonstration application for after-sales capability registration.",
                            IsActive = true,
                            Name = "Demo After-Sales Portal",
                            TenantId = new Guid("00000000-0000-0000-0000-000000000001")
                        });
                });

            modelBuilder.Entity("AfterSalesAI.Domain.IntegrationSource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConfigurationReference")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsReadOnly")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Protocol")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.HasIndex("TenantId", "ApplicationId");

                    b.HasIndex("TenantId", "ApplicationId", "Name")
                        .IsUnique();

                    b.ToTable("integration_sources", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000001"),
                            ApplicationId = new Guid("20000000-0000-0000-0000-000000000001"),
                            ConfigurationReference = "IntegrationSources__DemoOrderApi",
                            IsActive = true,
                            IsReadOnly = true,
                            Name = "Demo Order API",
                            Protocol = "REST",
                            TenantId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000002"),
                            ApplicationId = new Guid("20000000-0000-0000-0000-000000000001"),
                            ConfigurationReference = "IntegrationSources__DemoKnowledgeDatabase",
                            IsActive = true,
                            IsReadOnly = true,
                            Name = "Demo Knowledge Database",
                            Protocol = "SQLServer",
                            TenantId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Type = 2
                        });
                });

            modelBuilder.Entity("AfterSalesAI.Domain.KnowledgeChunk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ChunkIndex")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.HasIndex("DocumentId", "ChunkIndex")
                        .IsUnique();

                    b.HasIndex("TenantId", "ApplicationId", "DocumentId");

                    b.ToTable("knowledge_chunks", (string)null);
                });

            modelBuilder.Entity("AfterSalesAI.Domain.KnowledgeDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("SourcePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("UpdatedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.HasIndex("TenantId", "ApplicationId", "SourcePath")
                        .IsUnique();

                    b.ToTable("knowledge_documents", (string)null);
                });

            modelBuilder.Entity("AfterSalesAI.Domain.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("tenants", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            IsActive = true,
                            Name = "Demo After-Sales Tenant",
                            Region = "EU"
                        });
                });

            modelBuilder.Entity("AfterSalesAI.Domain.ToolDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("InputSchemaJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("IntegrationSourceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("OutputSchemaJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.HasIndex("IntegrationSourceId");

                    b.HasIndex("TenantId", "ApplicationId", "IsActive");

                    b.HasIndex("TenantId", "ApplicationId", "Name")
                        .IsUnique();

                    b.ToTable("tool_definitions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            ApplicationId = new Guid("20000000-0000-0000-0000-000000000001"),
                            Description = "Retrieve the current status of an order from an approved live system.",
                            InputSchemaJson = "{\"type\":\"object\",\"properties\":{\"query\":{\"type\":\"string\"}},\"required\":[\"query\"]}",
                            IntegrationSourceId = new Guid("30000000-0000-0000-0000-000000000001"),
                            IsActive = true,
                            Name = "get_order_status",
                            OutputSchemaJson = "{\"type\":\"object\"}",
                            TenantId = new Guid("00000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            ApplicationId = new Guid("20000000-0000-0000-0000-000000000001"),
                            Description = "Retrieve the current delivery status for an order.",
                            InputSchemaJson = "{\"type\":\"object\",\"properties\":{\"query\":{\"type\":\"string\"}},\"required\":[\"query\"]}",
                            IntegrationSourceId = new Guid("30000000-0000-0000-0000-000000000001"),
                            IsActive = true,
                            Name = "get_delivery_status",
                            OutputSchemaJson = "{\"type\":\"object\"}",
                            TenantId = new Guid("00000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            ApplicationId = new Guid("20000000-0000-0000-0000-000000000001"),
                            Description = "Search approved SOP and business process knowledge.",
                            InputSchemaJson = "{\"type\":\"object\",\"properties\":{\"query\":{\"type\":\"string\"}},\"required\":[\"query\"]}",
                            IntegrationSourceId = new Guid("30000000-0000-0000-0000-000000000002"),
                            IsActive = true,
                            Name = "search_sop",
                            OutputSchemaJson = "{\"type\":\"object\"}",
                            TenantId = new Guid("00000000-0000-0000-0000-000000000001")
                        });
                });

            modelBuilder.Entity("AfterSalesAI.Domain.Application", b =>
                {
                    b.HasOne("AfterSalesAI.Domain.Tenant", "Tenant")
                        .WithMany("Applications")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("AfterSalesAI.Domain.IntegrationSource", b =>
                {
                    b.HasOne("AfterSalesAI.Domain.Application", "Application")
                        .WithMany("IntegrationSources")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AfterSalesAI.Domain.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Application");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("AfterSalesAI.Domain.KnowledgeChunk", b =>
                {
                    b.HasOne("AfterSalesAI.Domain.Application", "Application")
                        .WithMany("KnowledgeChunks")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AfterSalesAI.Domain.KnowledgeDocument", "Document")
                        .WithMany("Chunks")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AfterSalesAI.Domain.Tenant", "Tenant")
                        .WithMany("KnowledgeChunks")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Application");

                    b.Navigation("Document");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("AfterSalesAI.Domain.KnowledgeDocument", b =>
                {
                    b.HasOne("AfterSalesAI.Domain.Application", "Application")
                        .WithMany("KnowledgeDocuments")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AfterSalesAI.Domain.Tenant", "Tenant")
                        .WithMany("KnowledgeDocuments")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Application");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("AfterSalesAI.Domain.ToolDefinition", b =>
                {
                    b.HasOne("AfterSalesAI.Domain.Application", "Application")
                        .WithMany("ToolDefinitions")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AfterSalesAI.Domain.IntegrationSource", "IntegrationSource")
                        .WithMany("ToolDefinitions")
                        .HasForeignKey("IntegrationSourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AfterSalesAI.Domain.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Application");

                    b.Navigation("IntegrationSource");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("AfterSalesAI.Domain.Application", b =>
                {
                    b.Navigation("IntegrationSources");

                    b.Navigation("KnowledgeChunks");

                    b.Navigation("KnowledgeDocuments");

                    b.Navigation("ToolDefinitions");
                });

            modelBuilder.Entity("AfterSalesAI.Domain.IntegrationSource", b =>
                {
                    b.Navigation("ToolDefinitions");
                });

            modelBuilder.Entity("AfterSalesAI.Domain.KnowledgeDocument", b =>
                {
                    b.Navigation("Chunks");
                });

            modelBuilder.Entity("AfterSalesAI.Domain.Tenant", b =>
                {
                    b.Navigation("Applications");

                    b.Navigation("KnowledgeChunks");

                    b.Navigation("KnowledgeDocuments");
                });
#pragma warning restore 612, 618
        }
    }
}
